### ISSUE TITLE
网络的训练权重

### ISSUE THREAD

**Issue by meiguiz** [jeffsonyu/VTacO#7]
您好！打扰了，我想要直接使用该项目，因为我并没有好的GPU进行训练。请问可以提供您已经训练完的权重文件嘛？万分感谢！包括python train_depth.py configs/tactile/tactile_test.yaml

**Comment by jeffsonyu** [comment]
Hi! The img-to-depth model checkpoint can be found in the following link. Thank you for your attention on our work!
https://drive.google.com/file/d/1bWg-avRw2yLtPrSiCJ0e-ZtKrh21vAmE/view?usp=drive_link

**Comment by meiguiz** [comment]
在VTacO_YCB.yaml文件里，encoder_hand是不是应该设置为False，在encoder_t2d下面的encoder_hand是不是同样应该设置为False，现在的VTacO_YCB.yaml的这两个设置均为True

**Comment by jeffsonyu** [comment]
Actually, the param **encoder_hand** can be set to **False** since we don't predict the hand param in VTacO pipeline. However, the **encoder_hand** under the **encoder_t2d_kwargs** should set to **True**, since we train the model_depth.pth with a hand param predictor. You can try to load the checkpoint with the **encoder_hand** True or False

**Comment by jeffsonyu** [comment]
Close due to no update
